# Generated by Django 4.2.3 on 2023-07-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('items', '0002_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='depth',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
