# Generated by Django 4.2.3 on 2023-07-20 04:39

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ('items', '0003_alter_item_depth_alter_item_height_alter_item_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
                ),
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=10)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryMapping',
            fields=[
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
                ),
                ('category_mapping_id', models.AutoField(primary_key=True, serialize=False)),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='category_mappings',
                        to='items.category',
                    ),
                ),
                (
                    'item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='category_mappings', to='items.item'
                    ),
                ),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
                ),
                ('color_id', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=10)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ColorMapping',
            fields=[
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
                ),
                ('color_mapping_id', models.AutoField(primary_key=True, serialize=False)),
                (
                    'color',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='color_mappings', to='items.color'
                    ),
                ),
                (
                    'item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='color_mappings', to='items.item'
                    ),
                ),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ItemTagMapping',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
