# Generated by Django 4.2.3 on 2023-07-20 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('buyers', '0002_alter_buyer_options_buyer_created_buyer_modified'),
        ('items', '0004_category_categorymapping_color_colormapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='buyer',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='buyers.buyer'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
