# Generated by Django 4.2.3 on 2023-07-31 07:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('items', '0007_alter_recentlyvieweditem_deleted_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentlyvieweditem',
            name='deleted_date',
        ),
    ]
