# Generated by Django 4.2.3 on 2023-08-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('items', '0008_remove_recentlyvieweditem_deleted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentlyvieweditem',
            name='deleted_date',
            field=models.DateTimeField(null=True),
        ),
    ]
