# Generated by Django 4.2.3 on 2023-09-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('items', '0009_recentlyvieweditem_deleted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='deleted_date',
            field=models.DateTimeField(null=True),
        ),
    ]
