# Generated by Django 4.2.3 on 2023-10-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('items', '0010_item_deleted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='end_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='start_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
