# Generated by Django 4.2.3 on 2023-10-03 10:59

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('sellers', '0005_alter_seller_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
                ),
                ('exhibition_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=46)),
                ('biography', models.CharField(max_length=255)),
                ('cover_image', models.FileField(upload_to='exhibitions/exhibition_cover_image/')),
                ('artist_image', models.FileField(upload_to='exhibitions/exhibition_artist_image/')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('background_color', models.CharField(max_length=10)),
                ('font_family', models.CharField(max_length=50)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sellers.seller')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExhibitionItem',
            fields=[
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
                ),
                ('exhibition_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=46)),
                ('description', models.CharField(max_length=255)),
                ('template', models.PositiveIntegerField()),
                ('is_sale', models.BooleanField()),
                ('position', models.IntegerField()),
                ('background_color', models.CharField(max_length=10)),
                ('font_family', models.CharField(max_length=50)),
                ('is_custom', models.BooleanField(default=False)),
                (
                    'exhibition',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='exhibition_items',
                        to='exhibitions.exhibition',
                    ),
                ),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExhibitionItemSound',
            fields=[
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
                ),
                ('exhibition_sound_id', models.AutoField(primary_key=True, serialize=False)),
                ('sound', models.FileField(upload_to='exhibitions/exhibition_item_sound/')),
                (
                    'exhibition_item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='exhibition_sounds',
                        to='exhibitions.exhibitionitem',
                    ),
                ),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExhibitionItemImage',
            fields=[
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
                ),
                ('exhibition_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='exhibitions/exhibition_item_image/')),
                (
                    'exhibition_item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='exhibition_images',
                        to='exhibitions.exhibitionitem',
                    ),
                ),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
