# Generated by Django 4.2.3 on 2023-10-05 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('exhibitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='artist_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
