# Generated by Django 4.2.3 on 2023-10-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('exhibitions', '0002_exhibition_artist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
