# Generated by Django 4.2.3 on 2023-10-06 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('sellers', '0005_alter_seller_email'),
        ('exhibitions', '0003_exhibition_is_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='seller',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='exhibitions', to='sellers.seller'
            ),
        ),
    ]
