# Generated by Django 4.2.3 on 2023-10-10 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('items', '0011_item_end_date_item_start_date'),
        ('exhibitions', '0004_alter_exhibition_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitionitem',
            name='item',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='exhibition_item',
                to='items.item',
            ),
        ),
    ]
