# Generated by Django 4.2.3 on 2023-10-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('exhibitions', '0005_exhibitionitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='status',
            field=models.CharField(default='생성', max_length=20),
        ),
    ]
