# Generated by Django 4.2.3 on 2023-10-12 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('items', '0011_item_end_date_item_start_date'),
        ('exhibitions', '0005_exhibitionitem_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitionitem',
            name='item',
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='exhibition_item',
                to='items.item',
            ),
        ),
    ]
