# Generated by Django 4.2.3 on 2023-10-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('exhibitions', '0006_alter_exhibitionitem_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitionitem',
            name='template',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
