# Generated by Django 4.2.3 on 2023-10-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('exhibitions', '0007_alter_exhibitionitem_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitionitem',
            name='background_color',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='exhibitionitem',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exhibitionitem',
            name='font_family',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exhibitionitem',
            name='title',
            field=models.CharField(max_length=46, null=True),
        ),
    ]
