# Generated by Django 4.2.3 on 2023-10-25 13:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('exhibitions', '0006_exhibition_status'),
        ('exhibitions', '0008_alter_exhibitionitem_background_color_and_more'),
    ]

    operations = []
