# Generated by Django 4.2.3 on 2023-10-19 02:44

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0004_alter_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='Unknown Address', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='Unknown Name', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='01000000000', max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='order',
            name='zipcode',
            field=models.CharField(default='00000', max_length=10),
        ),
    ]
