# Generated by Django 4.2.3 on 2023-10-19 03:27

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0005_order_address_order_name_order_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='01000000000', max_length=128, region='KR'),
        ),
    ]
