service: leporem-art

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10
  region: ap-northeast-2

functions:
  api:
    handler: leporem_art/asgi.handler
    events:
      - httpApi: '*'
    environment:
      ENV: ${opt:stage, 'dev'}

custom:
  customDomain:
    domainName: ${opt:stage, 'dev'}.leporem.art
    stage: ${opt:stage, 'dev'}
    basePath: ''
    createRoute53Record: false

plugins:
  - serverless-python-requirements
  - serverless-domain-manager

package:
  exclude:
    - node_modules/**
