service: leporem-art

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10
  region: ap-northeast-2

functions:
  api:
    handler: leporem_art/asgi.handler
    events:
      - httpApi: '*'
    environment:
      ENV: ${opt:stage, 'dev'}

plugins:
  - serverless-python-requirements

package:
  exclude:
    - node_modules/**
