# Generated by Django 4.2.3 on 2023-07-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sellers', '0002_alter_verifyemail_verify_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='description',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
