# Generated by Django 4.2.3 on 2023-09-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sellers', '0004_alter_seller_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='email',
            field=models.EmailField(max_length=50, null=True, unique=True),
        ),
    ]
