# Generated by Django 4.2.3 on 2023-07-31 06:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='user',
        ),
    ]
