# Generated by Django 4.2.3 on 2023-08-05 15:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('buyers', '0002_alter_buyer_options_buyer_created_buyer_modified'),
        ('sellers', '0004_alter_seller_temperature'),
        ('chats', '0002_rename_sender_message_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('buyer', 'seller')},
        ),
    ]
