# Generated by Django 4.2.3 on 2023-08-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chats', '0004_chatroom_uuid_message_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(
                choices=[
                    ('TEXT', '텍스트'),
                    ('IMAGE', '이미지'),
                    ('ITEM_SHARE', '작품 공유'),
                    ('ITEM_INQUIRY', '작품 문의'),
                    ('ORDER', '주문'),
                ],
                default='TEXT',
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
