# Generated by Django 4.2.3 on 2023-11-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chats', '0005_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(null=True, upload_to='chats/message_image/'),
        ),
    ]
