# Generated by Django 4.2.3 on 2023-07-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='user/profile_images/default.png', upload_to='user/profile_images/'),
        ),
    ]
