# Generated by Django 4.2.3 on 2023-08-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_useroauthinfo_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_agree_terms',
            field=models.BooleanField(default=False),
        ),
    ]
