name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql user: palindrome
          mysql password: ${{ secrets.MYSQL_PASSWORD }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --only dev

      - name: Run linters
        run: |
          poetry run flake8
          poetry run black --check .
          poetry run isort --check .

      - name: Run tests
        run: |
          poetry run pytest tests/*
