name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENV: test

    services:
      mysqldb:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run linters
        run: |
          poetry run flake8
          poetry run black --check .
          poetry run isort --check .

      - name: Run tests
        run: |
          poetry run pytest tests/*
