name: Deploy Swagger

on:
  push:
    branches:
      - develop

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: upload to s3
        run: aws s3 cp ./swagger.yaml s3://${{ secrets.AWS_DEV_BUCKET }}/swagger.yaml
