# Generated by Django 4.2.3 on 2023-09-19 05:06

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('users', '0006_user_is_agree_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
                ),
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('fcm_token', models.CharField(max_length=255, unique=True)),
                (
                    'user',
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='users.user'
                    ),
                ),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
