# Generated by Django 4.2.3 on 2023-09-20 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_user_is_agree_terms'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='user',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='users.user'
            ),
        ),
    ]
